import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Header } from "@/components/ui/header";
import { SearchBar } from "@/components/ui/search-bar";
import { AppWrapper } from "@/components/AppWrapper";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Bookable.",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="h-screen flex flex-col">
        <div>
          <Header />
          <SearchBar className="!flex md:!hidden px-4 py-2" />
        </div>
        
        {/* Sidebar and content area */}
        <div className="flex-1 flex overflow-hidden">
          <AppWrapper>{children}</AppWrapper>
        </div>
      </body>
    </html>
  );
}